# Generated by Django 5.1.3 on 2025-02-10 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_academicrecord_courses_academicrecord_courses'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_gov', models.CharField(max_length=100)),
                ('residential_address', models.CharField(max_length=100)),
                ('waec_result', models.FileField(upload_to='waec/')),
                ('jamb_result_slip', models.FileField(upload_to='jamb/')),
                ('de_result', models.FileField(blank=True, null=True, upload_to='de/')),
                ('mode_of_study', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time')], default='full-time', max_length=10)),
                ('admission_type', models.CharField(choices=[('utme', 'UTME'), ('direct-entry', 'Direct Entry'), ('transfer', 'Transfer')], default='utme', max_length=12)),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('relationship', models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('other', 'Other')], max_length=100, null=True)),
                ('guardian_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('guardian_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_address', models.CharField(blank=True, max_length=100, null=True)),
                ('disability', models.BooleanField(default=False)),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='birth_certificate/')),
                ('medical_certificate', models.FileField(blank=True, null=True, upload_to='medical_certificate/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.AddField(
            model_name='applicant',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screeningform',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_forms', to='core.applicant'),
        ),
        migrations.AddField(
            model_name='screeningform',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='accounts.faculty'),
        ),
    ]
