# Generated by Django 5.1.3 on 2025-02-20 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_academicrecord_courses_academicrecord_courses'),
        ('core', '0003_remove_screeningform_de_result_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screeningform',
            name='local_gov',
        ),
        migrations.AddField(
            model_name='screeningform',
            name='contact_address',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='screeningform',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='screeningform',
            name='declaration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='screeningform',
            name='email',
            field=models.EmailField(default='not_provided@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='screeningform',
            name='exam_number',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='screeningform',
            name='exam_year',
            field=models.IntegerField(default=2020),
        ),
        migrations.AddField(
            model_name='screeningform',
            name='first_choice',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_choices', to='accounts.faculty'),
        ),
        migrations.AddField(
            model_name='screeningform',
            name='first_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='screeningform',
            name='local_government',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='screeningform',
            name='middle_name',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='screeningform',
            name='olevel_type',
            field=models.CharField(choices=[('waec', 'WAEC'), ('neco', 'NECO')], default='waec', max_length=10),
        ),
        migrations.AddField(
            model_name='screeningform',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AddField(
            model_name='screeningform',
            name='second_choice',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_choices', to='accounts.faculty'),
        ),
        migrations.AddField(
            model_name='screeningform',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='screeningform',
            name='state_of_origin',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='screeningform',
            name='surname',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='screeningform',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='screeningform',
            name='birth_certificate',
            field=models.FileField(blank=True, default='default_birth_certificate.pdf', null=True, upload_to='birth_certificate/'),
        ),
        migrations.AlterField(
            model_name='screeningform',
            name='course',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='accounts.faculty'),
        ),
        migrations.AlterField(
            model_name='screeningform',
            name='guardian_address',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='screeningform',
            name='guardian_name',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='screeningform',
            name='guardian_occupation',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='screeningform',
            name='guardian_phone_number',
            field=models.CharField(blank=True, default='N/A', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='screeningform',
            name='jamb_result_slip',
            field=models.FileField(default='default_jamb.pdf', upload_to='jamb/'),
        ),
        migrations.AlterField(
            model_name='screeningform',
            name='medical_certificate',
            field=models.FileField(blank=True, default='default_medical_certificate.pdf', null=True, upload_to='medical_certificate/'),
        ),
        migrations.AlterField(
            model_name='screeningform',
            name='relationship',
            field=models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('other', 'Other')], default='other', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='screeningform',
            name='residential_address',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='screeningform',
            name='waec_result',
            field=models.FileField(default='default_waec.pdf', upload_to='waec/'),
        ),
    ]
