# Generated by Django 5.1.3 on 2025-02-20 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_academicrecord_courses_academicrecord_courses'),
        ('core', '0004_remove_screeningform_local_gov_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningform',
            name='third_choice',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_choices', to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='screeningform',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_forms', to='core.applicant'),
        ),
        migrations.AlterField(
            model_name='screeningform',
            name='first_choice',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_choices', to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='screeningform',
            name='second_choice',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_choices', to='accounts.department'),
        ),
    ]
