# Generated by Django 5.1.3 on 2025-02-20 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_academicrecord_courses_academicrecord_courses'),
        ('core', '0005_screeningform_third_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screeningform',
            name='disability',
        ),
        migrations.RemoveField(
            model_name='screeningform',
            name='medical_certificate',
        ),
        migrations.AddField(
            model_name='screeningform',
            name='passport_photo',
            field=models.FileField(default='test.docx', upload_to='passport/'),
        ),
        migrations.AlterField(
            model_name='screeningform',
            name='birth_certificate',
            field=models.FileField(blank=True, default='test.docx', null=True, upload_to='birth_certificate/'),
        ),
        migrations.AlterField(
            model_name='screeningform',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.faculty'),
        ),
        migrations.AlterField(
            model_name='screeningform',
            name='jamb_result_slip',
            field=models.FileField(default='test.docx', upload_to='jamb/'),
        ),
        migrations.AlterField(
            model_name='screeningform',
            name='waec_result',
            field=models.FileField(default='test.docx', upload_to='waec/'),
        ),
    ]
