# Generated by Django 5.1.3 on 2025-02-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_screeningform_disability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningform',
            name='jamb_score',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
