# Generated by Django 5.1.3 on 2025-02-21 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_screeningform_jamb_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screeningform',
            name='admission_type',
        ),
        migrations.RemoveField(
            model_name='screeningform',
            name='course',
        ),
        migrations.RemoveField(
            model_name='screeningform',
            name='mode_of_study',
        ),
    ]
