# Generated by Django 5.1.3 on 2025-02-21 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_screeningform_admission_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screeningform',
            name='guardian_address',
        ),
        migrations.RemoveField(
            model_name='screeningform',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='screeningform',
            name='guardian_occupation',
        ),
        migrations.RemoveField(
            model_name='screeningform',
            name='guardian_phone_number',
        ),
        migrations.RemoveField(
            model_name='screeningform',
            name='relationship',
        ),
    ]
