# Generated by Django 5.1.3 on 2025-02-21 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_screeningform_guardian_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screeningform',
            name='residential_address',
        ),
    ]
