# Generated by Django 5.1.3 on 2025-02-21 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_screeningform_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningform',
            name='exam_year',
            field=models.IntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
