# Generated by Django 5.1.3 on 2025-02-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_screeningform_exam_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('not_applied', 'Not Applied'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_applied', max_length=20),
        ),
    ]
