# Generated by Django 5.1.3 on 2025-02-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_applicant_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='status',
        ),
    ]
