# Generated by Django 5.1.11 on 2025-08-12 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_applicant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningform',
            name='dates_attended',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='screeningform',
            name='school_attended',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.CreateModel(
            name='AcademicSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('english', 'English Language'), ('mathematics', 'Mathematics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('economics', 'Economics'), ('literature', 'Literature in English'), ('government', 'Government'), ('history', 'History'), ('geography', 'Geography'), ('commerce', 'Commerce'), ('accounting', 'Accounting'), ('agriculture', 'Agricultural Science'), ('further_maths', 'Further Mathematics'), ('civic_education', 'Civic Education'), ('christian_religious_studies', 'Christian Religious Studies'), ('islamic_studies', 'Islamic Studies'), ('yoruba', 'Yoruba'), ('hausa', 'Hausa'), ('igbo', 'Igbo'), ('french', 'French'), ('arabic', 'Arabic'), ('food_and_nutrition', 'Food and Nutrition'), ('home_economics', 'Home Economics'), ('technical_drawing', 'Technical Drawing'), ('woodwork', 'Woodwork'), ('metalwork', 'Metalwork'), ('auto_mechanics', 'Auto Mechanics'), ('electronics', 'Electronics'), ('computer_studies', 'Computer Studies'), ('visual_arts', 'Visual Arts'), ('music', 'Music'), ('physical_education', 'Physical Education'), ('health_education', 'Health Education')], max_length=50)),
                ('grade', models.CharField(choices=[('A1', 'A1'), ('B2', 'B2'), ('B3', 'B3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('D7', 'D7'), ('E8', 'E8'), ('F9', 'F9')], max_length=2)),
                ('sitting', models.CharField(choices=[('first', 'First Sitting'), ('second', 'Second Sitting')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('screening_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_subjects', to='core.screeningform')),
            ],
            options={
                'ordering': ['subject'],
                'unique_together': {('screening_form', 'subject', 'sitting')},
            },
        ),
    ]
