# Generated by Django 5.1.11 on 2025-08-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_screeningform_dates_attended_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screeningform',
            old_name='school_attended',
            new_name='primary_school',
        ),
        migrations.RemoveField(
            model_name='screeningform',
            name='dates_attended',
        ),
        migrations.AddField(
            model_name='screeningform',
            name='primary_school_dates',
            field=models.CharField(default='N/A', help_text='Format: 2012-2018', max_length=20),
        ),
        migrations.AddField(
            model_name='screeningform',
            name='secondary_school',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='screeningform',
            name='secondary_school_dates',
            field=models.CharField(default='N/A', help_text='Format: 2018-2024', max_length=20),
        ),
    ]
