# Generated by Django 5.1.11 on 2025-08-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_school_attended_screeningform_primary_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningform',
            name='primary_school_dates',
            field=models.CharField(default='N/A', help_text='Format: 2012-2018', max_length=100),
        ),
        migrations.AlterField(
            model_name='screeningform',
            name='secondary_school_dates',
            field=models.CharField(default='N/A', help_text='Format: 2018-2024', max_length=100),
        ),
    ]
