# Generated by Django 5.1.3 on 2025-08-19 20:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_screeningform_primary_school_dates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screeningform',
            name='exam_number',
        ),
        migrations.RemoveField(
            model_name='screeningform',
            name='exam_year',
        ),
        migrations.RemoveField(
            model_name='screeningform',
            name='olevel_type',
        ),
        migrations.CreateModel(
            name='ExaminationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitting', models.CharField(choices=[('first', 'First Sitting'), ('second', 'Second Sitting')], max_length=10)),
                ('exam_type', models.CharField(choices=[('waec', 'WAEC'), ('neco', 'NECO'), ('nabteb', 'NABTEB'), ('gce', 'GCE')], max_length=10)),
                ('exam_number', models.CharField(max_length=20)),
                ('exam_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2025)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('screening_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_details', to='core.screeningform')),
            ],
            options={
                'ordering': ['sitting'],
                'unique_together': {('screening_form', 'sitting')},
            },
        ),
    ]
