# Generated by Django 5.1.3 on 2025-08-19 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_screeningform_exam_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examinationdetail',
            options={},
        ),
        migrations.RemoveField(
            model_name='examinationdetail',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='examinationdetail',
            name='exam_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='examinationdetail',
            name='exam_year',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='ScreeningPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=2000.0, max_digits=10)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('paystack_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_payments', to='core.applicant')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
