# Generated by Django 5.1.3 on 2025-08-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_examinationdetail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('nce', 'NCE'), ('diploma', 'Diploma'), ('degree', 'Degree')], default='nce', max_length=20),
        ),
    ]
