# Generated by Django 5.1.3 on 2025-08-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_program_program_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(choices=[('nce', 'NCE'), ('diploma', 'Diploma'), ('degree', 'Degree')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['program_type', 'name'],
                'unique_together': {('program_type', 'name')},
            },
        ),
    ]
