# Generated by Django 5.1.3 on 2025-08-20 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_programchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningform',
            name='first_choice',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_choices', to='core.programchoice'),
        ),
        migrations.AlterField(
            model_name='screeningform',
            name='second_choice',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_choices', to='core.programchoice'),
        ),
        migrations.AlterField(
            model_name='screeningform',
            name='third_choice',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_choices', to='core.programchoice'),
        ),
    ]
