# Generated by Django 5.2.9 on 2026-02-15 21:58

from django.db import migrations, models


def backfill_applicant_status(apps, schema_editor):
    """Set status to pending_review for applicants who already have screening forms"""
    Applicant = apps.get_model('core', 'Applicant')
    ScreeningForm = apps.get_model('core', 'ScreeningForm')
    Applicant.objects.filter(
        id__in=ScreeningForm.objects.values_list('applicant_id', flat=True)
    ).update(status='pending_review')


def reverse_backfill(apps, schema_editor):
    Applicant = apps.get_model('core', 'Applicant')
    Applicant.objects.filter(status='pending_review').update(status='not_applied')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_screeningform_first_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('not_applied', 'Not Applied'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_applied', max_length=20),
        ),
        migrations.RunPython(backfill_applicant_status, reverse_backfill),
    ]
