# Generated by Django 5.2.9 on 2026-02-16 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_applicant_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningform',
            name='birth_certificate_comment',
            field=models.TextField(blank=True, help_text='Comment if document is rejected', null=True),
        ),
        migrations.AddField(
            model_name='screeningform',
            name='birth_certificate_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', help_text='Verification status for birth certificate', max_length=20),
        ),
        migrations.AddField(
            model_name='screeningform',
            name='jamb_result_slip_comment',
            field=models.TextField(blank=True, help_text='Comment if document is rejected', null=True),
        ),
        migrations.AddField(
            model_name='screeningform',
            name='jamb_result_slip_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', help_text='Verification status for JAMB result slip', max_length=20),
        ),
        migrations.AddField(
            model_name='screeningform',
            name='passport_photo_comment',
            field=models.TextField(blank=True, help_text='Comment if document is rejected', null=True),
        ),
        migrations.AddField(
            model_name='screeningform',
            name='passport_photo_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', help_text='Verification status for passport photo', max_length=20),
        ),
        migrations.AddField(
            model_name='screeningform',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When documents were last verified/rejected', null=True),
        ),
        migrations.AddField(
            model_name='screeningform',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin who verified/rejected documents', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='screeningform',
            name='waec_result_comment',
            field=models.TextField(blank=True, help_text='Comment if document is rejected', null=True),
        ),
        migrations.AddField(
            model_name='screeningform',
            name='waec_result_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', help_text='Verification status for WAEC/NECO result', max_length=20),
        ),
    ]
