# Generated by Django 5.1.3 on 2025-02-14 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_supportrequest_is_replied_supportrequest_reply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='support_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.supportrequest'),
        ),
    ]
