# Generated by Django 5.1.3 on 2024-12-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentprofile_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='matriculation_number',
        ),
        migrations.AddField(
            model_name='user',
            name='matriculation_number',
            field=models.CharField(blank=True, help_text='Only applicable for students and staff.', max_length=20, null=True, unique=True),
        ),
    ]
