# Generated by Django 5.1.3 on 2024-12-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_studentprofile_matriculation_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='date_employed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
