# Generated by Django 5.1.3 on 2024-12-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_course_code_course_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('first', 'first'), ('second', 'second')], max_length=10),
        ),
    ]
