# Generated by Django 5.1.3 on 2025-01-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_courseregistration_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='current_semester',
            field=models.CharField(choices=[('first', 'First Semester'), ('second', 'Second Semester')], default='first', max_length=10),
        ),
    ]
