# Generated by Django 5.1.3 on 2025-01-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_paymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='faculty/'),
        ),
    ]
