# Generated by Django 5.1.3 on 2025-02-04 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
