# Generated by Django 5.1.3 on 2025-02-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicrecord',
            name='courses',
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='courses',
            field=models.ManyToManyField(related_name='academic_courses', to='accounts.course'),
        ),
    ]
