# Generated by Django 5.1.3 on 2026-02-07 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_academicsession_level_studentprofile_current_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.level'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='current_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.level'),
        ),
    ]
