# Generated by Django 5.1.3 on 2026-02-07 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_fields_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.academicsession'),
        ),
    ]
