# Generated by Django 5.1.3 on 2026-02-07 20:18

from django.db import migrations


def populate_course_sessions(apps, schema_editor):
    """Populate academic_session field for existing courses"""
    Course = apps.get_model('accounts', 'Course')
    AcademicSession = apps.get_model('accounts', 'AcademicSession')

    # Get the active session
    active_session = AcademicSession.objects.filter(is_active=True).first()
    if not active_session:
        # Fallback to 2023/2024 if no active session
        active_session = AcademicSession.objects.filter(name='2023/2024').first()

    if active_session:
        # Update all courses without an academic session
        Course.objects.filter(academic_session__isnull=True).update(academic_session=active_session)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_add_course_academic_session'),
    ]

    operations = [
        migrations.RunPython(populate_course_sessions, migrations.RunPython.noop),
    ]
