# Generated by Django 5.1.3 on 2026-02-07 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_populate_course_sessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Fee amount in Naira', max_digits=10)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='accounts.academicsession')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='accounts.department')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='accounts.level')),
            ],
            options={
                'verbose_name': 'Fee Structure',
                'verbose_name_plural': 'Fee Structures',
                'ordering': ['academic_session', 'department', 'level'],
                'unique_together': {('academic_session', 'department', 'level')},
            },
        ),
    ]
