# Generated by Django 5.2.9 on 2026-02-09 10:41

import django.db.models.deletion
from django.db import migrations, models


def create_course_offerings(apps, schema_editor):
    """Create CourseOffering records from existing Course data"""
    Course = apps.get_model('accounts', 'Course')
    CourseOffering = apps.get_model('accounts', 'CourseOffering')

    # Get all courses that have department and level data
    for course in Course.objects.all():
        # Check if course has the old fields (before migration)
        if hasattr(course, 'department') and hasattr(course, 'level'):
            if course.department and course.level:
                CourseOffering.objects.create(
                    course=course,
                    department=course.department,
                    level=course.level,
                    is_active=course.is_active
                )

def reverse_course_offerings(apps, schema_editor):
    """Reverse migration - not implemented as it's complex"""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_add_fee_structure'),
    ]

    operations = [
        # First create the CourseOffering model
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='accounts.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='accounts.department')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='accounts.level')),
            ],
            options={
                'verbose_name': 'Course Offering',
                'verbose_name_plural': 'Course Offerings',
                'ordering': ['course__code', 'department__name', 'level__order'],
                'unique_together': {('course', 'department', 'level')},
            },
        ),
        # Data migration to create CourseOffering records from existing data
        migrations.RunPython(create_course_offerings, reverse_code=reverse_course_offerings),
        # Remove the unique constraint
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        # Remove the old fields
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
    ]
