# Generated by Django 5.2.9 on 2026-02-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_add_course_offerings'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='programme_type',
            field=models.CharField(choices=[('degree', 'Degree'), ('nd', 'ND (Diploma)'), ('nce', 'NCE')], default='degree', help_text='Degree, ND (Diploma), or NCE', max_length=10),
        ),
        migrations.AddField(
            model_name='level',
            name='programme_type',
            field=models.CharField(choices=[('degree', 'Degree'), ('nd', 'ND (Diploma)'), ('nce', 'NCE')], default='degree', help_text='Degree (100-400), ND (ND1-ND2), or NCE (NCE1-NCE2)', max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='programme_type',
            field=models.CharField(choices=[('degree', 'Degree'), ('nd', 'ND (Diploma)'), ('nce', 'NCE')], default='degree', help_text='Degree, ND (Diploma), or NCE - determines which faculties/levels apply', max_length=10),
        ),
        migrations.AlterField(
            model_name='level',
            name='display_name',
            field=models.CharField(help_text="e.g., '100 Level', 'ND 1', 'NCE 1'", max_length=20),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(help_text="e.g., '100', '200', 'ND1', 'NCE1'", max_length=10, unique=True),
        ),
    ]
