# Generated by Django 5.2.9 on 2026-03-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_user_user_type_examofficerprofile_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='matriculation_number',
        ),
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, help_text='Student ID number (e.g., LCE/DIP/CMP/24/0001) or Staff ID. Manually assigned.', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='exam_score',
            field=models.DecimalField(decimal_places=1, help_text='Exam score out of 60', max_digits=4),
        ),
        migrations.AlterField(
            model_name='result',
            name='test_score',
            field=models.DecimalField(decimal_places=1, help_text='Test score out of 40', max_digits=4),
        ),
    ]
