# Generated by Django 5.2.9 on 2026-03-03 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_remove_user_matriculation_number_user_id_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseregistration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='accounts.academicsession'),
        ),
        migrations.AlterUniqueTogether(
            name='courseregistration',
            unique_together={('student', 'course', 'academic_session')},
        ),
    ]
